const fs = require('fs');
const path = require('path');

const pagesDir = 'c:/wamp64/www/hpci/pages';
const files = fs.readdirSync(pagesDir).filter(f => f.endsWith('.html'));

const replacements = [
    // Bio-nettoyage
    { from: "lenvironnement", to: "l'environnement" },
    { from: "dhygine", to: "d'hygiène" },
    { from: "d'hygine", to: "d'hygiène" },
    { from: "vidos", to: "vidéos" },
    { from: "Dsinfection", to: "Désinfection" },
    { from: "dcontamination", to: "décontamination" },
    { from: "prcision", to: "précision" },
    { from: "Prcision", to: "Précision" },
    { from: "certifis", to: "certifiés" },
    { from: "biodgradables", to: "biodégradables" },
    { from: "sant", to: "santé" },
    { from: "spcifiques", to: "spécifiques" },
    { from: "Traabilit", to: "Traçabilité" },
    { from: "complte", to: "complète" },
    { from: "oprations", to: "opérations" },
    { from: "dsinfection", to: "désinfection" },
    { from: "l'hygine", to: "l'hygiène" },
    { from: "scoeurit", to: "sécurité" },
    { from: "leves", to: "élevées" },
    { from: "rduire", to: "réduire" },
    { from: "lutilisation", to: "l'utilisation" },
    { from: "limpact", to: "l'impact" },
    { from: "Dmonstrations", to: "Démonstrations" },
    { from: "Accueil</a><span></span>", to: "Accueil</a><span>-</span>" },
    { from: "Services</a><span></span>", to: "Services</a><span>-</span>" },
    { from: "<li><span style=\"color: var(--red); font-weight: 800;\"></span>", to: "<li><span style=\"color: var(--red); font-weight: 800;\">-</span>" },
    
    // Nettoyage Pro
    { from: "productivit", to: "productivité" },
    { from: "bien-tre", to: "bien-être" },
    { from: "Qualit", to: "Qualité" },
    { from: "qualit", to: "qualité" },
    { from: "dentretien", to: "d'entretien" },
    { from: "limportance", to: "l'importance" },
    { from: "priodique", to: "périodique" },
    { from: "runion", to: "réunion" },
    { from: "dpoussirage", to: "dépoussiérage" },
    { from: "poussetage", to: "époussetage" },
    { from: "dcapage", to: "décapage" },
    { from: "spcialis", to: "spécialisé" },
    { from: "complte", to: "complète" },
    { from: "dchets", to: "déchets" },
    { from: "irrprochable", to: "irréprochable" },
    { from: "dgraissants", to: "dégraissants" },
    { from: "propret", to: "propreté" },
    { from: "rgulire", to: "régulière" },
    { from: "prservant", to: "préservant" },
    { from: "lesthtique", to: "l'esthétique" },
    { from: "fonctionnalit", to: "fonctionnalité" },
    { from: "durabilit", to: "durabilité" },
    { from: "Rsidences", to: "Résidences" },
    { from: "dappartements", to: "d'appartements" },
    { from: "proprits", to: "propriétés" },
    { from: "rsidentielles", to: "résidentielles" },
    { from: "pices", to: "pièces" },
    { from: " propos", to: "À propos" },
    { from: "dsherbage", to: "désherbage" },
    { from: "Dsinsectisation", to: "Désinsectisation" },
    { from: "Dratisation", to: "Dératisation" },
    { from: "adapte", to: "adaptée" },
    { from: "frquence", to: "fréquence" },
    
    // Maintenance
    { from: "dfaillances", to: "défaillances" },
    { from: "prventive", to: "préventive" },
    { from: "curative", to: "curative" },
    { from: "Ptrolier", to: "Pétrolier" },
    { from: "ptrolires", to: "pétrolières" },
    { from: "scurit", to: "sécurité" },
    { from: "scurise", to: "sécurisée" },
    { from: "matriel", to: "matériel" },
    { from: "ptroliers", to: "pétroliers" },
    { from: "rglementations", to: "réglementations" },
    { from: "matire", to: "matière" },
    { from: "fiabilit", to: "fiabilité" },
    { from: "longvit", to: "longévité" },
    { from: "quipements", to: "équipements" },
    { from: "mcanique", to: "mécanique" },
    { from: "dpanner", to: "dépanner" },
    { from: "systmes", to: "systèmes" },
    { from: "gnrateurs", to: "générateurs" },
    { from: "prcis", to: "précis" },
    { from: "contrle", to: "contrôle" },
    { from: "rparation", to: "réparation" },
    { from: "laide", to: "l'aide" },
    { from: "dquipements", to: "d'équipements" },
    { from: "Nnuphar", to: "Nénuphar" },
    { from: "crmeur", to: "Écrémeur" },
    { from: "rduit", to: "réduit" },
    { from: "arrts", to: "arrêts" },
    { from: "cots", to: "coûts" },
    { from: "bnficiez", to: "bénéficiez" },
    { from: "dune", to: "d'une" },
    { from: "pices", to: "pièces" },
    { from: "dtaches", to: "détachées" },
    { from: "tranquillit", to: "tranquillité" },
    { from: "desprit", to: "d'esprit" },
    
    // Phytosanitaire
    { from: "Scurit", to: "Sécurité" },
    { from: "Vgtale", to: "Végétale" },
    { from: "Sant", to: "Santé" },
    { from: "Vgtaux", to: "Végétaux" },
    { from: "prserver", to: "préserver" },
    { from: "maladies", to: "maladies" },
    { from: "ravageurs", to: "ravageurs" },
    { from: "mauvaises", to: "mauvaises" },
    { from: "herbes", to: "herbes" },
    { from: "prennit", to: "pérennité" },
    { from: "espaces", to: "espaces" },
    { from: "verts", to: "verts" },
    { from: "agricoles", to: "agricoles" },
    { from: "Dsherbage", to: "Désherbage" },
    { from: "Mthodes", to: "Méthodes" },
    { from: "cologiques", to: "écologiques" },
    { from: "chimiques", to: "chimiques" },
    { from: "contrler", to: "contrôler" },
    { from: "croissance", to: "croissance" },
    { from: "plantes", to: "plantes" },
    { from: "indsirables", to: "indésirables" },
    { from: "prvention", to: "prévention" },
    { from: "traitements", to: "traitements" },
    { from: "cibls", to: "ciblés" },
    { from: "protger", to: "protéger" },
    { from: "vgtation", to: "végétation" },
    { from: "fongiques", to: "fongiques" },
    { from: "bactriennes", to: "bactériennes" },
    { from: "Prservation", to: "Préservation" },
    { from: "biodiversit", to: "biodiversité" },
    { from: "privilgiant", to: "privilégiant" },
    { from: "solutions", to: "solutions" },
    { from: "respectueuses", to: "respectueuses" },
    { from: "lenvironnement", to: "l'environnement" },
    { from: "cosystmes", to: "écosystèmes" },
    { from: "locaux", to: "locaux" },
    { from: "dmarche", to: "démarche" },
    { from: "dagriculture", to: "d'agriculture" },
    { from: "raisonne", to: "raisonnée" },
    
    // Engineering
    { from: "cur", to: "coeur" },
    { from: "linnovation", to: "l'innovation" },
    { from: "LIngnierie", to: "L'ingénierie" },
    { from: "lindustrie", to: "l'industrie" },
    { from: "lingnierie", to: "l'ingénierie" },
    { from: "Il sagit", to: "Il s'agit" },
    { from: "lapplication", to: "l'application" },
    { from: "mathmatiques", to: "mathématiques" },
    { from: "dvelopper", to: "développer" },
    { from: "amliorer", to: "améliorer" },
    { from: "systmes", to: "systèmes" },
    { from: "Dveloppement", to: "Développement" },
    { from: "dfis", to: "défis" },
    { from: "cration", to: "création" },
    { from: "rseaux", to: "réseaux" },
    { from: "sophistiqus", to: "sophistiqués" },
    { from: "rpondre", to: "répondre" },
    { from: "socit", to: "société" },
    { from: "crer", to: "créer" },
    { from: "assiste", to: "assistée" },
    { from: "Intgration", to: "Intégration" },
    { from: "Comptences", to: "Compétences" },
    { from: "Ingnierie", to: "Ingénierie" },
    { from: "nergtique", to: "Énergétique" },
    { from: "Vtre", to: "Votre" },
    { from: "dfis", to: "défis" },

    // Misc
    { from: " ", to: "à " },
    { from: "", to: "-" } // Last resort for isolated  like in bullet points
];

files.forEach(file => {
    const filePath = path.join(pagesDir, file);
    let content = fs.readFileSync(filePath, 'utf-8');
    
    replacements.forEach(({from, to}) => {
        const searchStr = from.split('').join('\uFFFD');
        content = content.split(searchStr).join(to);
    });
    
    fs.writeFileSync(filePath, content, 'utf-8');
});

console.log('done');
